// Generated by CoffeeScript 1.12.7
#target aftereffects;
var _bake, _comp, _fitLayer, _layer;

_bake = function(comp) {
  var effect, i, j, layer, property, ref, results;
  comp.openInViewer();
  layer = _layer(comp, "Controller");
  layer.outPoint = 1 * layer.containingComp.frameDuration;
  results = [];
  for (i = j = 1, ref = layer.Effects.numProperties; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
    effect = layer.Effects.property(i);
    property = effect.property(1);
    if (property.canSetExpression && property.expressionEnabled) {
      property.selected = true;
    }
    results.push(app.executeCommand(app.findMenuCommandId("Convert Expression to Keyframes")));
  }
  return results;
};

_layer = function(composition, layerName) {
  if (typeof composition === "string") {
    composition = _comp(composition);
  }
  return esy.composition.first(composition, layerName);
};

_comp = function(compositionName) {
  return esy.project.first(compositionName);
};

_fitLayer = function(layer) {
  var compRatio, mediaRatio, scale, size;
  size = layer.sourceRectAtTime(0, false);
  compRatio = layer.containingComp.width / layer.containingComp.height;
  mediaRatio = layer.width / layer.height;
  if (mediaRatio > compRatio) {
    scale = layer.containingComp.width / size.width * 100;
  } else {
    scale = layer.containingComp.height / size.height * 100;
  }
  return layer.property("Scale").setValue([scale, scale]);
};
